# Generated by Django 3.0.4 on 2020-07-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_topic_onwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='onwer',
            new_name='owner',
        ),
    ]
